Repository EU-web-eucossa/s12022-ui, pull requests merged in 2022-10, with the labels that each got.

#8 Update Readme.md
  Readme.md
Labels: documentation

#9 Update Readme.md
  Readme.md
Labels: documentation

#10 Setup react project
  .eslintrc.json
  .github/workflows/codeql.yml
  .github/workflows/greetings.yml
  .github/workflows/label.yml
  .github/workflows/stale.yml
  .prettierrc.json
  README.md
  index.html
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/App.tsx
  src/components/Header.tsx
  src/helpers/TopScroll.tsx
  src/interfaces/router.d.ts
  src/layouts/BaseLayout.tsx
  src/main.tsx
  src/pages/AboutPage.tsx
  src/pages/ContactPage.tsx
  src/pages/Homepage.tsx
  src/pages/NotFound.tsx
  src/router/index.tsx
  src/router/routes.tsx
  src/vite-env.d.ts
  tailwind.config.cjs
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: enhancement

#12 Update README.md
  README.md
Labels: documentation

#13 Forinda patch 1
  README.md
Labels: documentation

#15 Change title color to blue
  src/components/Header.tsx
Labels: enhancement

#16 Merge braches
  src/components/Header.tsx
Labels: enhancement

#22 Add footer and single product page
  index.html
  src/components/Footer.tsx
  src/components/Header.tsx
  src/data/nav.tsx
  src/data/products.tsx
  src/helpers/slugify.tsx
  src/index.css
  src/layouts/BaseLayout.tsx
  src/pages/Homepage.tsx
  src/pages/SingleProductPage.tsx
  src/router/routes.tsx
Labels: enhancement

#25 Development
  package.json
  pnpm-lock.yaml
  public/Minimalist Orange Shopping Bag Market Logo 1.png
  public/logo.png
  public/logo.svg
  src/components/Footer.tsx
  src/components/Header.tsx
  src/layouts/BaseLayout.tsx
  src/main.tsx
  src/pages/NotFound.tsx
  src/router/index.tsx
  tailwind.config.cjs
  vite.config.ts
Labels: enhancement

#26 Development
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/Header.tsx
  src/index.css
  src/main.tsx
  src/pages/Homepage.tsx
  src/pages/SingleProductPage.tsx
  src/state/hooks/index.tsx
  src/state/slices/cartSlice.tsx
  src/state/slices/productsSlice.tsx
  src/state/slices/userSlice.tsx
  src/state/store/index.tsx
  src/types/index.d.ts
  tailwind.config.cjs
Labels: enhancement

#27 Development
  src/components/CategoryProductItem.tsx
  src/components/Homecategories.tsx
  src/components/HomecategoryItem.tsx
  src/pages/CategoriesPage.tsx
  src/pages/Homepage.tsx
Labels: enhancement

#28 Fix cart add and remove
  src/components/Cart.tsx
  src/components/CategoryProductItem.tsx
  src/components/Header.tsx
  src/pages/CartPage.tsx
  src/state/slices/cartSlice.tsx
  src/types/index.d.ts
Labels: enhancement

#29 Development
  src/components/Cart.tsx
  src/components/Header.tsx
  src/components/Homecategories.tsx
  src/data/products.tsx
  src/interfaces/product.d.ts
  src/pages/CategoriesPage.tsx
Labels: enhancement

#30 Fix duplicate keys products
  src/components/CategoryProductItem.tsx
  src/components/Header.tsx
  src/data/products.tsx
  src/pages/CategoriesPage.tsx
Labels: bug-fix

#35 Add feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#34 Add bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, enhancement

#38 Development
  src/pages/SingleProductPage.tsx
Labels: bug-fix

#44 add login and signup pages
  public/vite.svg
  src/assets/react.svg
  src/components/InputElement.tsx
  src/components/PasswordElement.tsx
  src/layouts/BaseLayout.tsx
  src/pages/LoginPage.tsx
  src/pages/SignupPage.tsx
  src/router/index.tsx
  src/router/routes.tsx
Labels: enhancement

#51 Fix project deploy build error
  src/data/products.tsx
  src/state/slices/whiteListSlice.tsx
Labels: bug-fix

#52 Build fix #production
  src/data/products.tsx
  src/state/slices/whiteListSlice.tsx
Labels: bug-fix

#53 Add blur to cart
  src/components/Cart.tsx
  src/components/Header.tsx
  src/pages/Homepage.tsx
  src/pages/SingleProductPage.tsx
Labels: Feature add

#55 refined input and checkbox
  src/components/InputElement.tsx
  src/components/PasswordElement.tsx
  src/pages/LoginPage.tsx
Labels: enhancement

#58 Category filter
  src/components/CategoryProductItem.tsx
  src/components/Header.tsx
  src/components/HomeProductCategoriesRow.tsx
  src/components/HomeproductItem.tsx
  src/data/products.tsx
  src/index.css
  src/interfaces/product.d.ts
  src/pages/CategoriesPage.tsx
  src/pages/Homepage.tsx
  src/pages/SingleProductPage.tsx
  src/router/routes.tsx
  tailwind.config.cjs
Labels: enhancement, Feature add

#62 Dev adero
  src/components/Footer.tsx
Labels: enhancement
